"""
src/dataloader.py
-----------------
DataLoader factory for XMTL. Builds train/val/test DataLoaders from
pre-computed split indices (generated by preprocessing.py).

Supports modality masking for ablation studies.

Usage:
    from src.dataloader import build_dataloaders
    train_dl, val_dl, test_dl = build_dataloaders(cfg)
"""

import os
import sys
import numpy as np
import torch
from torch.utils.data import DataLoader
from types import SimpleNamespace
from typing import Dict, Optional, Tuple

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_DIR = os.path.dirname(_SCRIPT_DIR)
if _PROJECT_DIR not in sys.path:
    sys.path.insert(0, _PROJECT_DIR)

from src.dataset import XMTLDataset, load_shared_data


def _load_splits(cfg: SimpleNamespace) -> Dict[str, np.ndarray]:
    """Load pre-computed split indices from the processed directory.

    Args:
        cfg: Config namespace.

    Returns:
        Dict with keys 'train', 'val', 'test' mapping to index arrays.

    Raises:
        FileNotFoundError if split file does not exist (run preprocessing first).
    """
    processed_dir = cfg.data.processed_dir
    if not os.path.isabs(processed_dir):
        processed_dir = os.path.join(_PROJECT_DIR, processed_dir)

    seed = cfg.training.seed
    split_path = os.path.join(processed_dir, f"splits_seed{seed}.npz")

    if not os.path.isfile(split_path):
        raise FileNotFoundError(
            f"Split file not found: {split_path}\n"
            f"Run `python -m src.preprocessing --config configs/default.yaml` first."
        )

    data = np.load(split_path)
    return {"train": data["train"], "val": data["val"], "test": data["test"]}


def build_dataloaders(
    cfg: SimpleNamespace,
    modality_mask: Optional[Dict[str, bool]] = None,
) -> Tuple[DataLoader, DataLoader, DataLoader]:
    """Build train, validation, and test DataLoaders.

    Args:
        cfg:            Config namespace.
        modality_mask:  Optional dict to zero-mask modalities for ablation.
                        Example: {"visual": False} disables visual features.

    Returns:
        Tuple of (train_loader, val_loader, test_loader).
    """
    splits = _load_splits(cfg)

    # Load data once, share across all splits (saves ~3GB RAM)
    shared_data = load_shared_data(cfg)
    content_features = shared_data[0]

    # Compute global standardization stats from training set only
    train_content = content_features[splits["train"]]
    content_mean = train_content.mean(axis=0).astype(np.float32)
    content_std = train_content.std(axis=0).astype(np.float32)
    # Avoid division by zero for constant features
    content_std[content_std < 1e-8] = 1.0
    content_stats = (content_mean, content_std)

    train_ds = XMTLDataset(cfg, indices=splits["train"], modality_mask=modality_mask, shared_data=shared_data, content_stats=content_stats)
    val_ds = XMTLDataset(cfg, indices=splits["val"], modality_mask=modality_mask, shared_data=shared_data, content_stats=content_stats)
    test_ds = XMTLDataset(cfg, indices=splits["test"], modality_mask=modality_mask, shared_data=shared_data, content_stats=content_stats)

    bs = cfg.training.batch_size
    nw = cfg.training.num_workers

    # Only pin memory when CUDA is available
    import torch
    pin = torch.cuda.is_available()

    train_loader = DataLoader(
        train_ds, batch_size=bs, shuffle=True,
        num_workers=nw, pin_memory=pin, drop_last=False,
    )
    val_loader = DataLoader(
        val_ds, batch_size=bs, shuffle=False,
        num_workers=nw, pin_memory=pin, drop_last=False,
    )
    test_loader = DataLoader(
        test_ds, batch_size=bs, shuffle=False,
        num_workers=nw, pin_memory=pin, drop_last=False,
    )

    return train_loader, val_loader, test_loader


# ============================================================================
# Minimal runnable example
# ============================================================================

if __name__ == "__main__":
    from utils.config import load_config

    cfg = load_config("configs/default.yaml")
    print("Building dataloaders...")
    train_dl, val_dl, test_dl = build_dataloaders(cfg)

    print(f"Train: {len(train_dl.dataset)} samples, {len(train_dl)} batches")
    print(f"Val:   {len(val_dl.dataset)} samples, {len(val_dl)} batches")
    print(f"Test:  {len(test_dl.dataset)} samples, {len(test_dl)} batches")

    # Fetch one batch and print shapes
    batch = next(iter(train_dl))
    print("\n--- Sample batch shapes ---")
    for key, val in batch.items():
        print(f"  {key:20s}: {val.shape}  dtype={val.dtype}")
